theme: minima
title: Lucy's Blog
url: "https://lucyjefford.github.io/my-blog/"
author: Lucy Jefford

# Site settings
baseurl: / # Change this to your relative path (ex: /blog), or leave just a /
markdown: kramdown
source: .
destination: ./_site
paginate: 8
paginate_path: /page:num/
permalink: /:title/
date_format: "%b %-d, %Y"

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
