theme: minima
title: Lucy's Blog
url: "https://lucyjefford.github.io/my-blog/"
author: 
  name: Lucy Jefford"
  email: "lucyj@hotmail.co.uk"

# Site settings
baseurl: / # Change this to your relative path (ex: /blog), or leave just a /
markdown: kramdown
source: .
destination: ./_site
paginate: 8
paginate_path: /page:num/
permalink: /:title/
date_format: "%b %-d, %Y"

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Options
custom_header: true
custom_nav_footer: true
reverse: false
